#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Frontend tesztelés - böngészőben ellenőrzés
"""

print("=== Frontend tesztelés - Böngészőben ellenőrzés ===")
print()
print("1. Nyisd meg a böngészőt: http://localhost:5000")
print()
print("2. Ellenőrizd a következő funkciókat:")
print()
print("   A) Adatminőség ellenőrzés gomb:")
print("      - Keressd meg a 'Adatminőség ellenőrzés' gombot")
print("      - Kattints rá és várj a validáció befejezésére")
print("      - Ellenőrizd, hogy megjelennek-e a minőség információk")
print()
print("   B) Dátum szűrő dropdown:")
print("      - Keressd meg a 'Minden dátum' dropdown-ot")
print("      - Válaszd ki a 'Ma', 'Elmúlt 7 nap' opciókat")
print("      - Ellenőrizd, hogy változnak-e a megjelenített állások")
print()
print("   C) Minőség információk panel:")
print("      - Keressd meg a kék színű minőség információkat")
print("      - Ellenőrizd a Pozíció, Cég, Lokáció, Átlagos minőség értékeket")
print("      - Ellenőrizd a színkódolt badge-eket (zöld/sárga/kék/piros)")
print()
print("   D) Job kártyák validációs adatok:")
print("      - Keressd meg a job kártyákat")
print("      - Ellenőrizd a minőség badge-eket (Kiváló/Jó/Közepes/Gyenge/Rossz)")
print("      - Ellenőrizd a 'Adatminőség' részben a konfidencia pontszámokat")
print()
print("   E) Excel export funkciók:")
print("      - Keressd meg a 'Excel export' gombot")
print("      - Keressd meg a 'Szűrt Excel' gombot")
print("      - Kattints rá és ellenőrizd a letöltést")
print()
print("   F) Szűrők működése:")
print("      - Teszteld a keresési szűrőt")
print("      - Teszteld a lokáció szűrőt")
print("      - Teszteld a munkavégzés típusa szűrőt")
print("      - Teszteld a fizetés szűrőt")
print("      - Teszteld a rendezési opciókat")
print()
print("   G) Pagináció:")
print("      - Ellenőrizd az oldalszámozást")
print("      - Teszteld az 'Előző'/'Következő' gombokat")
print("      - Ellenőrizd az állások számának megjelenítését")
print()
print("3. Ellenőrizd a következő UI elemeket:")
print()
print("   A) Főcím és navigáció:")
print("      - 'IT Álláskereső' főcím")
print("      - 'Keresés indítása' gomb")
print("      - 'Szűrők törlése' gomb")
print()
print("   B) Szűrő panel:")
print("      - Keresési mező")
print("      - Dátum szűrő dropdown")
print("      - Lokáció szűrő dropdown")
print("      - Munkavégzés típusa szűrő dropdown")
print("      - Fizetés szűrő dropdown")
print("      - Rendezés szűrő dropdown")
print()
print("   C) Eredmények panel:")
print("      - Állások száma badge")
print("      - Export gombok (CSV, Excel, Szűrt Excel)")
print("      - Adatminőség ellenőrzés gomb")
print("      - Minőség információk panel")
print()
print("   D) Job kártyák:")
print("      - Pozíció címe (linkkel)")
print("      - Cég neve")
print("      - Lokáció")
print("      - Fizetés (ha van)")
print("      - Munkavégzés típusa (ha van)")
print("      - Leírás")
print("      - Publikálás dátuma")
print("      - Validációs információk")
print("      - Minőség badge")
print("      - 'Megtekintés' gomb")
print()
print("   E) Pagináció:")
print("      - Oldalszámok")
print("      - 'Előző'/'Következő' gombok")
print("      - Állások száma megjelenítés")
print()
print("=== Frontend tesztelés befejezve ===")
print()
print("Ha a Flask alkalmazás nem fut:")
print("1. Ellenőrizd a terminálban a szintaxis hibákat")
print("2. Javítsd ki a hibákat")
print("3. Indítsd el újra: python app.py")
print()
print("Ha a Flask alkalmazás fut, de nem elérhető:")
print("1. Ellenőrizd a portot: http://localhost:5000")
print("2. Ellenőrizd a tűzfal beállításokat")
print("3. Próbáld meg: http://127.0.0.1:5000")
