#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
No Fluff Jobs frontend integráció tesztelése
"""

print("=== No Fluff Jobs frontend integráció tesztelése ===")
print()
print("1. Nyisd meg a böngészőt: http://localhost:5000")
print()
print("2. Ellenőrizd a következő változtatásokat:")
print()
print("   A) Főcím módosítása:")
print("      - Ellenőrizd, hogy a címsorban szerepel-e: 'IT Álláskereső - Profession.hu & No Fluff Jobs'")
print("      - Ellenőrizd, hogy a navigációs sávban szerepel-e: 'Profession.hu & No Fluff Jobs'")
print()
print("   B) Portál választó:")
print("      - Keressd meg a 'Scrapelhető portálok' szekciót")
print("      - Ellenőrizd, hogy szerepel-e a 'No Fluff Jobs' portál")
print("      - Ellenőrizd, hogy 'Aktív' státuszú-e")
print("      - Ellenőrizd, hogy 'IT specializált álláskereső portál - Magyar felület' leírással")
print()
print("   C) No Fluff Jobs tesztelő gomb:")
print("      - Keressd meg a 'No Fluff Jobs teszt' gombot")
print("      - Ellenőrizd, hogy zöld színű és 'flask' ikonnal")
print("      - Kattints rá és várj a tesztelés befejezésére")
print("      - Ellenőrizd, hogy megjelennek-e a No Fluff Jobs állások")
print()
print("   D) Állások megjelenítése:")
print("      - Ellenőrizd, hogy a 'Forrás' oszlopban szerepel-e 'No Fluff Jobs'")
print("      - Ellenőrizd, hogy a linkek 'nofluffjobs.com' domain-re mutatnak")
print("      - Ellenőrizd, hogy megjelennek-e a pozíciók, cégek, lokációk")
print()
print("3. Ha a Flask alkalmazás nem fut:")
print("   - Ellenőrizd a terminálban a szintaxis hibákat")
print("   - Javítsd ki a hibákat")
print("   - Indítsd el újra: python app.py")
print()
print("4. Ha a Flask alkalmazás fut, de nem elérhető:")
print("   - Ellenőrizd a portot: http://localhost:5000")
print("   - Ellenőrizd a tűzfal beállításokat")
print("   - Próbáld meg: http://127.0.0.1:5000")
print()
print("=== Tesztelés befejezve ===")
